<?php
include('config.php');
if(empty($_SESSION['uid']))
{
header("Location: index.php");
}
include('userClass.php');
$userClass = new userClass();
$secret=$userClass->usercode($_SESSION['uid']);
$email=$userClass->useremail($_SESSION['uid']);

require_once 'GoogleAuthenticator.php';
$ga = new GoogleAuthenticator();
$qrCodeUrl = $ga->getQRCodeGoogleUrl($email, $secret,'Your Application Name');
//HTML Code
?>


Enter the verification code generated by Google Authenticator app on your phone.
<div id="img">
<img src='<?php echo $qrCodeUrl; ?>' />
</div>

<form method="post" action="home.php">
<label>Enter Google Authenticator Code</label>
<input type="text" name="code" />
<input type="submit" class="button"/>
</form>
